import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://192.168.6.8:3001/');
  await page.goto('http://192.168.6.8:3001/login');
  await page.getByPlaceholder('Enter email address').click();
  await page.getByPlaceholder('Enter email address').fill('saagar@gmail.com');
  await page.getByPlaceholder('Enter Password').click();
  await page.getByPlaceholder('Enter Password').fill('Vijay@123');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByPlaceholder('Please enter your first name').click();
  await page.getByPlaceholder('Please enter your first name').fill('vijay');
  await page.getByPlaceholder('Please enter your last name').click();
  await page.getByPlaceholder('Please enter your last name').fill('anand');
  await page.locator('#Experience div').filter({ hasText: 'Select...' }).first().click();
  await page.locator('.css-qbdosj-Input').first().click();
  await page.locator('.css-qbdosj-Input').first().click();
  await page.locator('#react-select-2-input').fill('1');
  await page.locator('div').filter({ hasText: /^1$/ }).nth(2).click();
  await page.locator('.css-4gi536-control > .css-bbf1rh-ValueContainer > .css-qbdosj-Input').click();
  await page.locator('#react-select-3-input').fill('frontend');
  await page.getByText('Frontend', { exact: true }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: '+ Add' }).click();
  await page.getByPlaceholder('Please enter the summary').fill('add summary');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByText('+ Add').click();
  await page.getByPlaceholder('Please enter the summary').fill('second summary');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('.css-qbdosj-Input').first().click();
  await page.locator('#react-select-4-input').fill('react js');
  await page.locator('#react-select-4-option-0 div').first().click();
  await page.locator('.css-bbf1rh-ValueContainer > .css-qbdosj-Input').first().click();
  await page.locator('#react-select-5-input').fill('mysql');
  await page.locator('#react-select-5-option-0 div').first().click();
  await page.locator('.css-bbf1rh-ValueContainer > .css-qbdosj-Input').first().click();
  await page.locator('#react-select-6-input').fill('lambda');
  await page.locator('#react-select-6-option-9 div').first().click();
  await page.locator('.css-bbf1rh-ValueContainer > .css-qbdosj-Input').first().click();
  await page.locator('#react-select-7-input').fill('jira');
  await page.locator('#react-select-7-option-0 div').first().click();
  await page.locator('.css-bbf1rh-ValueContainer > .css-qbdosj-Input').click();
  await page.locator('#react-select-8-input').fill('git');
  await page.locator('div').filter({ hasText: /^Git$/ }).nth(2).click();
  await page.getByRole('button', { name: 'Next' }).click();
   
  await page.locator('.css-qbdosj-Input').click();
  await page.locator('#react-select-9-input').fill('react js');
  await page.getByText('React JS', { exact: true }).click();
  await page.getByPlaceholder('Ex: 1 year 2 months').click();
  await page.getByPlaceholder('Ex: 1 year 2 months').fill('1 month');
  await page.getByRole('button', { name: '+ Add' }).first().click();
  await page.getByPlaceholder('Please enter the summary').fill('sum');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: '+ Add' }).nth(1).click();
  await page.getByPlaceholder('Please enter the summary').fill('response');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  const page1 = await page1Promise;
});